### ISSUE TITLE
Research Request - Bus Service Increase 2023-24

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#885] opened 2023-09-19 23:39 UTC
## Research Question
**Single sentence** description:  
Rebuild #164 for v2 warehouse. Also generate and catalog new insights.

**Detailed** description:

- [ ] How many routes meet service target by operator?
- [ ] Where are there missing routes?
- [ ] How can GTFS data inform service coordination and/or consolidation, especially in urban areas?

## Deliverables:
Notebook, dashboard, narrative, presentation details.

## Timeline of deliverables:
Estimated completion date

**Comment by tiffanychu90** [comment] 2023-12-12 17:48
* Include costs and estimates of increase in ridership (tweak model from AHSC, Katrina / Shweta's work)

**Comment by tiffanychu90** [comment] 2024-01-30 17:31
1/30/24: SB 125 mtg update. We can continue to use NTD 2019 values for `cost_of_bus`. Reproduce the service density vs CalEnviroScreen tracts (but swap CalEnviroScreen -> RHNA by tracts) to identify where there's enough density to support more service but doesn't have enough service

**Comment by tiffanychu90** [comment] 2024-06-07 16:21
Closing because dataset was given to McK related to this

**Closed by tiffanychu90** 2024-06-07 16:21 UTC
Labels: research request, SB125
